/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soli_jnistudy_JniTest */

#ifndef _Included_com_soli_jnistudy_JniTest
#define _Included_com_soli_jnistudy_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soli_jnistudy_JniTest
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_soli_jnistudy_JniTest_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
