/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_barswipe_jni_Jnidemo */

#ifndef _Included_com_barswipe_jni_Jnidemo
#define _Included_com_barswipe_jni_Jnidemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_barswipe_jni_Jnidemo
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_barswipe_jni_Jnidemo_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
